"use client";

import { useState } from "react";
import { useAction } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { getErrorMessage } from "@/lib/utils";

// Import the words from A1.txt
const A1_WORDS = [
  "ab",
  "abfahren",
  "die Abfahrt",
  "abgeben",
  "abholen",
  "der Absender",
  "Achtung",
  "die Adresse",
  "alles",
  "alle",
  "allein",
  "also",
  "alt",
  "das Alter",
  "an",
  "anbieten",
  "das Angebot",
  "ander-",
  "anfangen",
  "der Anfang",
  "anklicken",
  "ankommen",
  "die Ankunft",
  "ankreuzen",
  "anmachen",
  "sich anmelden",
  "die Anmeldung",
  "die Anrede",
  "anrufen",
  "der Anruf",
  "der Anrufbeantworter",
  "die Ansage",
  "der Anschluss",
  "an sein",
  "antworten",
  "die Antwort",
  "die Anzeige",
  "sich anziehen",
  "das Apartment",
  "der Apfel",
  "der Appetit",
  "arbeiten",
  "die Arbeit",
  "arbeitslos",
  "der Arbeitsplatz",
  "der Arm",
  "der Arzt",
  "auch",
  "auf",
  "die Aufgabe",
  "aufhören",
  "auf sein",
  "aufstehen",
  "der Aufzug",
  "das Auge",
  "aus",
  "der Ausflug",
  "ausfüllen",
  "der Ausgang",
  "die Auskunft",
  "das Ausland",
  "der Ausländer",
  "ausländisch",
  "ausmachen",
  "die Aussage",
  "aussehen",
  "aus sein",
  "aussteigen",
  "der Ausweis",
  "sich ausziehen",
  "das Auto",
  "die Autobahn",
  "der Automat",
  "automatisch",
  "das Baby",
  "die Bäckerei",
  "das Bad",
  "baden",
  "die Bahn",
  "der Bahnhof",
  "der Bahnsteig",
  "bald",
  "der Balkon",
  "die Banane",
  "die Bank",
  "bar",
  "der Bauch",
  "der Baum",
  "der Beamte",
  "bedeuten",
  "beginnen",
  "bei",
  "beide",
  "das Bein",
  "das Beispiel",
  "bekannt",
  "der/die Bekannte",
  "bekommen",
  "benutzen",
  "der Beruf",
  "besetzt",
  "besichtigen",
  "besser",
  "best-",
  "bestellen",
  "besuchen",
  "das Bett",
  "bezahlen",
  "das Bier",
  "das Bild",
  "billig",
  "die Birne",
  "bis",
  "bisschen",
  "bitte",
  "die Bitte",
  "bitten",
  "bitter",
  "bleiben",
  "der Bleistift",
  "der Blick",
  "die Blume",
  "der Bogen",
  "böse",
  "brauchen",
  "breit",
  "der Brief",
  "die Briefmarke",
  "bringen",
  "das Brot",
  "das Brötchen",
  "der Bruder",
  "das Buch",
  "der Buchstabe",
  "buchstabieren",
  "der Bus",
  "die Butter",
  "das Café",
  "die CD",
  "der Chef",
  "circa",
  "der Computer",
  "da",
  "die Dame",
  "daneben",
  "danken",
  "der Dank",
  "danke",
  "dann",
  "das Datum",
  "dauern",
  "dein-",
  "denn",
  "der/die/das",
  "dich",
  "dies-",
  "dir",
  "die Disco",
  "der Doktor",
  "das Doppelzimmer",
  "das Dorf",
  "dort",
  "draußen",
  "drucken",
  "der Drucker",
  "drücken",
  "durch",
  "die Durchsage",
  "dürfen",
  "der Durst",
  "sich duschen",
  "die Dusche",
  "die Ecke",
  "die Ehefrau",
  "der Ehemann",
  "das Ei",
  "eilig",
  "ein-",
  "einfach",
  "der Eingang",
  "einkaufen",
  "einladen",
  "die Einladung",
  "einmal",
  "einsteigen",
  "der Eintritt",
  "das Einzelzimmer",
  "die Eltern",
  "die E-Mail",
  "der Empfänger",
  "empfehlen",
  "enden",
  "das Ende",
  "entschuldigen",
  "die Entschuldigung",
  "er",
  "das Ergebnis",
  "erklären",
  "erlauben",
  "der Erwachsene",
  "erzählen",
  "es",
  "essen",
  "das Essen",
  "euer",
  "fahren",
  "der Fahrer",
  "die Fahrkarte",
  "das Fahrrad",
  "falsch",
  "die Familie",
  "der Familienname",
  "der Familienstand",
  "die Farbe",
  "das Fax",
  "Feier-",
  "feiern",
  "fehlen",
  "der Fehler",
  "fernsehen",
  "fertig",
  "das Feuer",
  "das Fieber",
  "der Film",
  "finden",
  "die Firma",
  "der Fisch",
  "die Flasche",
  "das Fleisch",
  "fliegen",
  "abfliegen",
  "der Abflug",
  "der Flughafen",
  "das Flugzeug",
  "das Formular",
  "das Foto",
  "fragen",
  "die Frage",
  "die Frau",
  "frei",
  "die Freizeit",
  "fremd",
  "sich freuen",
  "der Freund",
  "die Freundin",
  "früher",
  "frühstücken",
  "das Frühstück",
  "die Führung",
  "für",
  "der Fuß",
  "der Fußball",
  "der Garten",
  "der Gast",
  "geben",
  "geboren",
  "das Geburtsjahr",
  "der Geburtsort",
  "der Geburtstag",
  "gefallen",
  "gegen",
  "gehen",
  "gehören",
  "das Geld",
  "das Gemüse",
  "das Gepäck",
  "gerade",
  "geradeaus",
  "gern",
  "das Geschäft",
  "das Geschenk",
  "die Geschwister",
  "das Gespräch",
  "gestern",
  "gestorben",
  "das Getränk",
  "das Gewicht",
  "gewinnen",
  "das Glas",
  "glauben",
  "gleich",
  "das Gleis",
  "das Glück",
  "glücklich",
  "der Glückwunsch",
  "Grad",
  "gratulieren",
  "grillen",
  "groß",
  "die Größe",
  "die Großeltern",
  "die Großmutter",
  "der Großvater",
  "die Gruppe",
  "der Gruß",
  "gültig",
  "günstig",
  "gut",
  "das Haar",
  "haben",
  "das Hähnchen",
  "die Halbpension",
  "die Halle",
  "hallo",
  "halten",
  "die Haltestelle",
  "die Hand",
  "das Handy",
  "das Haus",
  "die Hausaufgabe",
  "die Hausfrau",
  "der Hausmann",
  "die Heimat",
  "heiraten",
  "heißen",
  "helfen",
  "hell",
  "der Herd",
  "der Herr",
  "herzlich",
  "heute",
  "hier",
  "die Hilfe",
  "hinten",
  "das Hobby",
  "hoch",
  "die Hochzeit",
  "holen",
  "hören",
  "das Hotel",
  "der Hund",
  "der Hunger",
  "ich",
  "ihr",
  "ihm",
  "ihn",
  "immer",
  "in",
  "die Information",
  "international",
  "das Internet",
  "ja",
  "die Jacke",
  "jed-",
  "jetzt",
  "der Job",
  "der Jugendliche",
  "jung",
  "der Junge",
  "der Kaffee",
  "kaputt",
  "die Karte",
  "die Kreditkarte",
  "die Kartoffel",
  "die Kasse",
  "kaufen",
  "kein",
  "kennen",
  "kennenlernen",
  "das Kind",
  "der Kindergarten",
  "das Kino",
  "der Kiosk",
  "klar",
  "die Klasse",
  "die Kleidung",
  "klein",
  "kochen",
  "der Koffer",
  "der Kollege",
  "die Kollegin",
  "kommen",
  "können",
  "das Konto",
  "der Kopf",
  "kosten",
  "krank",
  "kriegen",
  "die Küche",
  "der Kuchen",
  "der Kugelschreiber",
  "der Kühlschrank",
  "kulturell",
  "sich kümmern",
  "der Kunde",
  "die Kundin",
  "der Kurs",
  "kurz",
  "lachen",
  "der Laden",
  "das Land",
  "lang",
  "lange",
  "langsam",
  "laufen",
  "laut",
  "leben",
  "das Leben",
  "die Lebensmittel",
  "ledig",
  "legen",
  "der Lehrer",
  "die Lehrerin",
  "leicht",
  "leider",
  "leise",
  "lernen",
  "lesen",
  "letzt-",
  "die Leute",
  "das Licht",
  "lieb-",
  "lieben",
  "lieber",
  "Lieblings-",
  "das Lied",
  "liegen",
  "links",
  "der Lkw",
  "das Lokal",
  "die Lösung",
  "lustig",
  "machen",
  "das Mädchen",
  "man",
  "der Mann",
  "männlich",
  "die Maschine",
  "das Meer",
  "mehr",
  "mein",
  "meist-",
  "der Mensch",
  "mieten",
  "die Miete",
  "die Milch",
  "mit",
  "mitbringen",
  "mitkommen",
  "mitmachen",
  "mitnehmen",
  "die Mitte",
  "die Möbel",
  "möchten",
  "mögen",
  "möglich",
  "der Moment",
  "morgen",
  "müde",
  "der Mund",
  "müssen",
  "die Mutter",
  "nach",
  "nächst-",
  "der Name",
  "nehmen",
  "nein",
  "neu",
  "nicht",
  "nichts",
  "nie",
  "noch",
  "normal",
  "die Nummer",
  "nur",
  "oben",
  "das Obst",
  "oder",
  "öffnen",
  "geöffnet",
  "oft",
  "ohne",
  "das Öl",
  "die Oma",
  "der Opa",
  "die Ordnung",
  "der Ort",
  "das Papier",
  "die Papiere",
  "der Partner",
  "die Partnerin",
  "die Party",
  "der Pass",
  "die Pause",
  "der Plan",
  "der Platz",
  "die Polizei",
  "die Pommes frites",
  "die Post",
  "die Postleitzahl",
  "das Praktikum",
  "die Praxis",
  "der Preis",
  "das Problem",
  "der Prospekt",
  "die Prüfung",
  "pünktlich",
  "Rad fahren",
  "rauchen",
  "der Raum",
  "die Rechnung",
  "rechts",
  "regnen",
  "der Regen",
  "der Reis",
  "reisen",
  "die Reise",
  "das Reisebüro",
  "der Reiseführer",
  "reparieren",
  "die Reparatur",
  "das Restaurant",
  "die Rezeption",
  "richtig",
  "riechen",
  "ruhig",
  "der Saft",
  "sagen",
  "der Salat",
  "das Salz",
  "der Satz",
  "die S-Bahn",
  "der Schalter",
  "scheinen",
  "schicken",
  "das Schild",
  "der Schinken",
  "schlafen",
  "schlecht",
  "schließen",
  "geschlossen",
  "der Schluss",
  "der Schlüssel",
  "schmecken",
  "schnell",
  "schon",
  "schön",
  "der Schrank",
  "schreiben",
  "der Schuh",
  "die Schule",
  "der Schüler",
  "die Schülerin",
  "schwer",
  "die Schwester",
  "schwimmen",
  "das Schwimmbad",
  "der See",
  "sehen",
  "die Sehenswürdigkeit",
  "sehr",
  "sein",
  "an sein",
  "auf sein",
  "weg sein",
  "zu sein",
  "seit",
  "selbstständig",
  "sich",
  "sie",
  "sie (formal)",
  "sitzen",
  "so",
  "das Sofa",
  "sofort",
  "der Sohn",
  "sollen",
  "die Sonne",
  "spät",
  "später",
  "die Speisekarte",
  "spielen",
  "der Sport",
  "die Sprache",
  "sprechen",
  "die Stadt",
  "stehen",
  "die Stelle",
  "stellen",
  "der Stock",
  "die Straße",
  "die Straßenbahn",
  "studieren",
  "das Studium",
  "der Student",
  "die Stunde",
  "suchen",
  "tanzen",
  "die Tasche",
  "das Taxi",
  "der Tee",
  "der Teil",
  "telefonieren",
  "das Telefon",
  "der Termin",
  "der Test",
  "teuer",
  "der Text",
  "das Thema",
  "das Ticket",
  "der Tisch",
  "die Tochter",
  "die Toilette",
  "die Tomate",
  "tot",
  "sich treffen",
  "die Treppe",
  "trinken",
  "tschüss",
  "tun",
  "über",
  "übernachten",
  "überweisen",
  "die Uhr",
  "um",
  "umziehen",
  "und",
  "unser-",
  "unten",
  "unter",
  "der Unterricht",
  "unterschreiben",
  "die Unterschrift",
  "der Urlaub",
  "der Vater",
  "verboten",
  "verdienen",
  "der Verein",
  "verheiratet",
  "verkaufen",
  "der Verkäufer",
  "die Verkäuferin",
  "vermieten",
  "der Vermieter",
  "verstehen",
  "der Verwandte",
  "viel",
  "vielleicht",
  "von",
  "vor",
  "der Vorname",
  "die Vorsicht",
  "sich vorstellen",
  "die Vorwahl",
  "wandern",
  "wann",
  "warten",
  "warum",
  "was",
  "was für ein",
  "sich waschen",
  "das Wasser",
  "weh tun",
  "weiblich",
  "der Wein",
  "weit",
  "weiter",
  "welch-",
  "die Welt",
  "wenig",
  "wer",
  "werden",
  "das Wetter",
  "wichtig",
  "wie",
  "wiederholen",
  "das Wiederhören",
  "das Wiedersehen",
  "wie viel",
  "willkommen",
  "der Wind",
  "wir",
  "wissen",
  "wo",
  "woher",
  "wohin",
  "wohnen",
  "die Wohnung",
  "wollen",
  "das Wort",
  "wunderbar",
  "zahlen",
  "die Zeit",
  "zurzeit",
  "die Zeitung",
  "die Zigarette",
  "das Zimmer",
  "der Zoll",
  "zu",
  "zufrieden",
  "der Zug",
  "zurück",
  "zusammen",
  "zwischen",
];

export function BulkWordAdder() {
  const [isLoading, setIsLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [currentWord, setCurrentWord] = useState("");
  const [results, setResults] = useState<{
    success: number;
    failed: number;
    errors: string[];
  }>({ success: 0, failed: 0, errors: [] });

  const addNewWord = useAction(api.functions.words.addNewWord);

  const handleBulkAdd = async () => {
    setIsLoading(true);
    setProgress(0);
    setResults({ success: 0, failed: 0, errors: [] });

    const totalWords = A1_WORDS.length;
    let successCount = 0;
    let failedCount = 0;
    const errors: string[] = [];

    for (let i = 0; i < totalWords; i++) {
      const word = A1_WORDS[i];
      setCurrentWord(word);
      setProgress((i / totalWords) * 100);

      try {
        const result = await addNewWord({ word });
        if (result.success) {
          successCount++;
        } else {
          failedCount++;
          errors.push(`${word}: ${result.suggestions?.join(", ") || "Unknown error"}`);
        }
      } catch (error) {
        failedCount++;
        const errorMessage = getErrorMessage(error, "Unknown error");
        errors.push(`${word}: ${errorMessage}`);

        // Show toast for immediate feedback
        toast.error(`Failed to analyze "${word}": ${errorMessage}`);
      }
    }

    setProgress(100);
    setResults({ success: successCount, failed: failedCount, errors });
    setIsLoading(false);
  };

  return (
    <Card className="w-full max-w-2xl">
      <CardHeader>
        <CardTitle>Bulk Word Adder (A1 Words)</CardTitle>
        <CardDescription>
          Add all {A1_WORDS.length} A1 German words to the database. This will process each word
          through AI to get translations and metadata.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isLoading && (
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span>Progress: {Math.round(progress)}%</span>
              <span>Current: {currentWord}</span>
            </div>
            <Progress value={progress} className="w-full" />
          </div>
        )}

        {!isLoading && progress === 0 && (
          <Button onClick={handleBulkAdd} className="w-full">
            Start Adding {A1_WORDS.length} Words
          </Button>
        )}

        {!isLoading && progress === 100 && (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4 text-center">
              <div className="p-4 bg-green-50 rounded-lg">
                <div className="text-2xl font-bold text-green-600">{results.success}</div>
                <div className="text-sm text-green-600">Successfully Added</div>
              </div>
              <div className="p-4 bg-red-50 rounded-lg">
                <div className="text-2xl font-bold text-red-600">{results.failed}</div>
                <div className="text-sm text-red-600">Failed</div>
              </div>
            </div>

            {results.errors.length > 0 && (
              <div className="space-y-2">
                <h4 className="font-medium text-sm">Failed Words:</h4>
                <div className="max-h-40 overflow-y-auto space-y-1">
                  {results.errors.map((error, index) => (
                    <div key={index} className="text-xs text-red-600 bg-red-50 p-2 rounded">
                      {error}
                    </div>
                  ))}
                </div>
              </div>
            )}

            <Button onClick={handleBulkAdd} variant="outline" className="w-full">
              Run Again
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
